<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ChromiumProcessExplorer.Core\ChromiumProcessExplorer.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ChromiumProcessExplorer</AssemblyName>
    <ApplicationIcon>Assets\ChromiumProcessExplorer.ico</ApplicationIcon>
    <AssemblyTitle>Chromium Process Explorer</AssemblyTitle>
    <Product>Chromium Process Explorer</Product>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\ChromiumProcessExplorer.ico" />
  </ItemGroup>

</Project>
