param(
    [string]$SourceUrl = "https://peter.sh/experiments/chromium-command-line-switches/",
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\src\ChromiumProcessExplorer.Gui\ChromiumCommandLineCatalog.g.cs")
)

$ErrorActionPreference = "Stop"

$html = (Invoke-WebRequest -Uri $SourceUrl -UseBasicParsing).Content
$rowPattern = [regex]::new(
    '<tr>\s*<td><span class="(?<kind>feature|switch)">[^<]+</span></td>\s*<td>(?<name>.*?)</td>\s*<td>(?<description>.*?)</td>\s*<td>\s*<a href="(?<source>[^"]+)"',
    [System.Text.RegularExpressions.RegexOptions]::IgnoreCase -bor
    [System.Text.RegularExpressions.RegexOptions]::Singleline)

function ConvertFrom-HtmlFragment([string]$Value) {
    $withoutTags = [regex]::Replace($Value, '<[^>]+>', ' ')
    $decoded = [System.Net.WebUtility]::HtmlDecode($withoutTags)
    return [regex]::Replace($decoded, '\s+', ' ').Trim()
}

function ConvertTo-CSharpString([string]$Value) {
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    $escaped = $escaped.Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $escaped + '"'
}

$entries = foreach ($match in $rowPattern.Matches($html)) {
    $kind = $match.Groups["kind"].Value.ToLowerInvariant()
    $name = ConvertFrom-HtmlFragment $match.Groups["name"].Value
    $description = ConvertFrom-HtmlFragment $match.Groups["description"].Value
    if ($description -eq "No description…") {
        $description = ""
    }

    $argument = if ($kind -eq "feature") {
        "--enable-features=$name"
    } else {
        $name
    }

    [pscustomobject]@{
        Kind = if ($kind -eq "feature") { "Feature" } else { "Switch" }
        Name = $name
        Argument = $argument
        Description = $description
        Source = [System.Net.WebUtility]::HtmlDecode($match.Groups["source"].Value)
    }
}

if ($entries.Count -lt 1000) {
    throw "Only $($entries.Count) entries were parsed; the source HTML structure may have changed."
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("// <auto-generated />")
[void]$builder.AppendLine("// Generated by tools\GenerateChromiumCommandLineCatalog.ps1")
[void]$builder.AppendLine("// Source: $SourceUrl")
[void]$builder.AppendLine()
[void]$builder.AppendLine("namespace ChromiumProcessExplorer.Gui;")
[void]$builder.AppendLine()
[void]$builder.AppendLine("public static class ChromiumCommandLineCatalog")
[void]$builder.AppendLine("{")
[void]$builder.AppendLine("    public static IReadOnlyList<ChromiumCommandLineCatalogEntry> Entries { get; } =")
[void]$builder.AppendLine("    [")
foreach ($entry in $entries) {
    [void]$builder.AppendLine("        new(")
    [void]$builder.AppendLine("            $(ConvertTo-CSharpString $entry.Kind),")
    [void]$builder.AppendLine("            $(ConvertTo-CSharpString $entry.Name),")
    [void]$builder.AppendLine("            $(ConvertTo-CSharpString $entry.Argument),")
    [void]$builder.AppendLine("            $(ConvertTo-CSharpString $entry.Description),")
    [void]$builder.AppendLine("            $(ConvertTo-CSharpString $entry.Source)),")
}
[void]$builder.AppendLine("    ];")
[void]$builder.AppendLine("}")

$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($resolvedOutput)) | Out-Null
[System.IO.File]::WriteAllText(
    $resolvedOutput,
    $builder.ToString(),
    [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated $($entries.Count) Chromium command-line catalog entries at $resolvedOutput"
